#!/usr/bin/env python3
"""Regenerate THIRD_PARTY_NOTICES.md from the built image.

    python3 scripts/third-party-notices.py [image]   # default ghcr.io/artcashin/rss-feedhandler:latest

Asks the image, with the standard library only, for every installed
distribution and the licence text its wheel carries. The image is what ships,
so the image is what is read. Rerun after `make buildx`.
"""
import json, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IMAGE = sys.argv[1] if len(sys.argv) > 1 else "ghcr.io/artcashin/rss-feedhandler:latest"
DUMP = r'''
import importlib.metadata as m, json, sys
rows = []
for d in m.distributions():
    meta = d.metadata
    lic = meta.get("License-Expression") or ""
    if not lic:
        cls = [c.split("::")[-1].strip() for c in (meta.get_all("Classifier") or []) if c.startswith("License ::")]
        raw = meta.get("License") or ""
        lic = cls[0] if cls else (raw if raw and len(raw) <= 60 and "\n" not in raw else ("see licence text" if raw else "Unknown"))
    texts = []
    for f in d.files or []:
        n = f.name.lower()
        if ".dist-info" in str(f) and (n.startswith(("license", "licence", "copying", "notice")) or "/licenses/" in str(f).lower()):
            try: texts.append(f.read_binary().decode("utf-8", "replace").strip())
            except Exception: pass
    rows.append({"name": meta.get("Name"), "version": meta.get("Version"), "license": lic,
                 "home": meta.get("Home-page") or "", "texts": texts})
json.dump(sorted(rows, key=lambda r: ((r["name"] or "").lower(), r["version"] or "")), sys.stdout)
'''
created = subprocess.run(["docker", "image", "inspect", IMAGE, "--format", "{{.Created}}"],
                         capture_output=True, text=True, check=True).stdout.strip()[:10]
rows = json.loads(subprocess.run(["docker", "run", "--rm", "-i", IMAGE, "python", "-"], input=DUMP,
                                 capture_output=True, text=True, check=True).stdout)
own = {"rss-ticker", "rss_ticker", "rss-feedhandler"}
rows = [r for r in rows if (r["name"] or "").lower() not in own]
out = [
    "# Third-party notices", "",
    "rss-feedhandler is MIT (see `LICENSE`). Its image bundles the open-source work",
    "below, each under its own licence, reproduced here as those licences require.",
    f"Generated by `python3 scripts/third-party-notices.py` from `{IMAGE}` (built {created},",
    f"{len(rows)} distributions); do not edit by hand. The base image is `python:3.12-slim`",
    "(Python Software Foundation License; Debian packages under their own licences).", "",
]
for r in rows:
    out += [f"## {r['name']} {r['version']}", "", f"Licence: {r['license']}" + (f" · {r['home']}" if r["home"] else ""), ""]
    for t in r["texts"] or []:
        out += ["```", t, "```", ""]
    if not r["texts"]:
        out += ["_The wheel ships no licence file; the licence is as declared above._", ""]
(ROOT / "THIRD_PARTY_NOTICES.md").write_text("\n".join(out))
print(f"{len(rows)} distributions from {IMAGE} -> THIRD_PARTY_NOTICES.md")
